name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Check if minor/patch update
      id: check-update
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const title = context.payload.pull_request.title;
          
          // Check if it's a minor or patch update
          const isMinorPatch = /bump .* from .* to .*\.(0|[1-9]\d*)\.(0|[1-9]\d*)/.test(title);
          const isSecurity = title.includes('security') || title.includes('vulnerability');
          
          return isMinorPatch || isSecurity ? 'true' : 'false';
          
    - name: Auto-approve PR
      if: steps.check-update.outputs.result == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE',
            body: '✅ Auto-approved minor/patch dependency update or security fix'
          });
          
    - name: Enable auto-merge
      if: steps.check-update.outputs.result == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash',
            commit_title: context.payload.pull_request.title,
            commit_message: 'Auto-merged by Dependabot workflow after tests passed'
          });
          
    - name: Comment on major updates
      if: steps.check-update.outputs.result == 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: '⚠️ This appears to be a major version update. Please review manually before merging.'
          });